# CMAKE generated file: DO NOT EDIT!
# Generated by "MinGW Makefiles" Generator, CMake Version 3.31

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

SHELL = cmd.exe

# The CMake executable.
CMAKE_COMMAND = "C:\Program Files\CMake\bin\cmake.exe"

# The command to remove a file.
RM = "C:\Program Files\CMake\bin\cmake.exe" -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = C:\Users\nepte\Documents\GitHub\Agenda

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = C:\Users\nepte\Documents\GitHub\Agenda

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	"C:\Program Files\CMake\bin\cmake-gui.exe" -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	"C:\Program Files\CMake\bin\cmake.exe" --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start C:\Users\nepte\Documents\GitHub\Agenda\CMakeFiles C:\Users\nepte\Documents\GitHub\Agenda\\CMakeFiles\progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start C:\Users\nepte\Documents\GitHub\Agenda\CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named AgendaApp

# Build rule for target.
AgendaApp: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 AgendaApp
.PHONY : AgendaApp

# fast build rule for target.
AgendaApp/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\AgendaApp.dir\build.make CMakeFiles/AgendaApp.dir/build
.PHONY : AgendaApp/fast

src/Agenda/Agenda.obj: src/Agenda/Agenda.cpp.obj
.PHONY : src/Agenda/Agenda.obj

# target to build an object file
src/Agenda/Agenda.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\AgendaApp.dir\build.make CMakeFiles/AgendaApp.dir/src/Agenda/Agenda.cpp.obj
.PHONY : src/Agenda/Agenda.cpp.obj

src/Agenda/Agenda.i: src/Agenda/Agenda.cpp.i
.PHONY : src/Agenda/Agenda.i

# target to preprocess a source file
src/Agenda/Agenda.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\AgendaApp.dir\build.make CMakeFiles/AgendaApp.dir/src/Agenda/Agenda.cpp.i
.PHONY : src/Agenda/Agenda.cpp.i

src/Agenda/Agenda.s: src/Agenda/Agenda.cpp.s
.PHONY : src/Agenda/Agenda.s

# target to generate assembly for a file
src/Agenda/Agenda.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\AgendaApp.dir\build.make CMakeFiles/AgendaApp.dir/src/Agenda/Agenda.cpp.s
.PHONY : src/Agenda/Agenda.cpp.s

src/Agenda/Controller.obj: src/Agenda/Controller.cpp.obj
.PHONY : src/Agenda/Controller.obj

# target to build an object file
src/Agenda/Controller.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\AgendaApp.dir\build.make CMakeFiles/AgendaApp.dir/src/Agenda/Controller.cpp.obj
.PHONY : src/Agenda/Controller.cpp.obj

src/Agenda/Controller.i: src/Agenda/Controller.cpp.i
.PHONY : src/Agenda/Controller.i

# target to preprocess a source file
src/Agenda/Controller.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\AgendaApp.dir\build.make CMakeFiles/AgendaApp.dir/src/Agenda/Controller.cpp.i
.PHONY : src/Agenda/Controller.cpp.i

src/Agenda/Controller.s: src/Agenda/Controller.cpp.s
.PHONY : src/Agenda/Controller.s

# target to generate assembly for a file
src/Agenda/Controller.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\AgendaApp.dir\build.make CMakeFiles/AgendaApp.dir/src/Agenda/Controller.cpp.s
.PHONY : src/Agenda/Controller.cpp.s

src/Events/Event.obj: src/Events/Event.cpp.obj
.PHONY : src/Events/Event.obj

# target to build an object file
src/Events/Event.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\AgendaApp.dir\build.make CMakeFiles/AgendaApp.dir/src/Events/Event.cpp.obj
.PHONY : src/Events/Event.cpp.obj

src/Events/Event.i: src/Events/Event.cpp.i
.PHONY : src/Events/Event.i

# target to preprocess a source file
src/Events/Event.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\AgendaApp.dir\build.make CMakeFiles/AgendaApp.dir/src/Events/Event.cpp.i
.PHONY : src/Events/Event.cpp.i

src/Events/Event.s: src/Events/Event.cpp.s
.PHONY : src/Events/Event.s

# target to generate assembly for a file
src/Events/Event.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\AgendaApp.dir\build.make CMakeFiles/AgendaApp.dir/src/Events/Event.cpp.s
.PHONY : src/Events/Event.cpp.s

src/Events/EventsList.obj: src/Events/EventsList.cpp.obj
.PHONY : src/Events/EventsList.obj

# target to build an object file
src/Events/EventsList.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\AgendaApp.dir\build.make CMakeFiles/AgendaApp.dir/src/Events/EventsList.cpp.obj
.PHONY : src/Events/EventsList.cpp.obj

src/Events/EventsList.i: src/Events/EventsList.cpp.i
.PHONY : src/Events/EventsList.i

# target to preprocess a source file
src/Events/EventsList.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\AgendaApp.dir\build.make CMakeFiles/AgendaApp.dir/src/Events/EventsList.cpp.i
.PHONY : src/Events/EventsList.cpp.i

src/Events/EventsList.s: src/Events/EventsList.cpp.s
.PHONY : src/Events/EventsList.s

# target to generate assembly for a file
src/Events/EventsList.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\AgendaApp.dir\build.make CMakeFiles/AgendaApp.dir/src/Events/EventsList.cpp.s
.PHONY : src/Events/EventsList.cpp.s

src/Main.obj: src/Main.cpp.obj
.PHONY : src/Main.obj

# target to build an object file
src/Main.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\AgendaApp.dir\build.make CMakeFiles/AgendaApp.dir/src/Main.cpp.obj
.PHONY : src/Main.cpp.obj

src/Main.i: src/Main.cpp.i
.PHONY : src/Main.i

# target to preprocess a source file
src/Main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\AgendaApp.dir\build.make CMakeFiles/AgendaApp.dir/src/Main.cpp.i
.PHONY : src/Main.cpp.i

src/Main.s: src/Main.cpp.s
.PHONY : src/Main.s

# target to generate assembly for a file
src/Main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\AgendaApp.dir\build.make CMakeFiles/AgendaApp.dir/src/Main.cpp.s
.PHONY : src/Main.cpp.s

src/MultiString.obj: src/MultiString.cpp.obj
.PHONY : src/MultiString.obj

# target to build an object file
src/MultiString.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\AgendaApp.dir\build.make CMakeFiles/AgendaApp.dir/src/MultiString.cpp.obj
.PHONY : src/MultiString.cpp.obj

src/MultiString.i: src/MultiString.cpp.i
.PHONY : src/MultiString.i

# target to preprocess a source file
src/MultiString.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\AgendaApp.dir\build.make CMakeFiles/AgendaApp.dir/src/MultiString.cpp.i
.PHONY : src/MultiString.cpp.i

src/MultiString.s: src/MultiString.cpp.s
.PHONY : src/MultiString.s

# target to generate assembly for a file
src/MultiString.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\AgendaApp.dir\build.make CMakeFiles/AgendaApp.dir/src/MultiString.cpp.s
.PHONY : src/MultiString.cpp.s

src/ResourceManager.obj: src/ResourceManager.cpp.obj
.PHONY : src/ResourceManager.obj

# target to build an object file
src/ResourceManager.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\AgendaApp.dir\build.make CMakeFiles/AgendaApp.dir/src/ResourceManager.cpp.obj
.PHONY : src/ResourceManager.cpp.obj

src/ResourceManager.i: src/ResourceManager.cpp.i
.PHONY : src/ResourceManager.i

# target to preprocess a source file
src/ResourceManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\AgendaApp.dir\build.make CMakeFiles/AgendaApp.dir/src/ResourceManager.cpp.i
.PHONY : src/ResourceManager.cpp.i

src/ResourceManager.s: src/ResourceManager.cpp.s
.PHONY : src/ResourceManager.s

# target to generate assembly for a file
src/ResourceManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\AgendaApp.dir\build.make CMakeFiles/AgendaApp.dir/src/ResourceManager.cpp.s
.PHONY : src/ResourceManager.cpp.s

src/Timestamp/Date.obj: src/Timestamp/Date.cpp.obj
.PHONY : src/Timestamp/Date.obj

# target to build an object file
src/Timestamp/Date.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\AgendaApp.dir\build.make CMakeFiles/AgendaApp.dir/src/Timestamp/Date.cpp.obj
.PHONY : src/Timestamp/Date.cpp.obj

src/Timestamp/Date.i: src/Timestamp/Date.cpp.i
.PHONY : src/Timestamp/Date.i

# target to preprocess a source file
src/Timestamp/Date.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\AgendaApp.dir\build.make CMakeFiles/AgendaApp.dir/src/Timestamp/Date.cpp.i
.PHONY : src/Timestamp/Date.cpp.i

src/Timestamp/Date.s: src/Timestamp/Date.cpp.s
.PHONY : src/Timestamp/Date.s

# target to generate assembly for a file
src/Timestamp/Date.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\AgendaApp.dir\build.make CMakeFiles/AgendaApp.dir/src/Timestamp/Date.cpp.s
.PHONY : src/Timestamp/Date.cpp.s

src/Timestamp/Time.obj: src/Timestamp/Time.cpp.obj
.PHONY : src/Timestamp/Time.obj

# target to build an object file
src/Timestamp/Time.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\AgendaApp.dir\build.make CMakeFiles/AgendaApp.dir/src/Timestamp/Time.cpp.obj
.PHONY : src/Timestamp/Time.cpp.obj

src/Timestamp/Time.i: src/Timestamp/Time.cpp.i
.PHONY : src/Timestamp/Time.i

# target to preprocess a source file
src/Timestamp/Time.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\AgendaApp.dir\build.make CMakeFiles/AgendaApp.dir/src/Timestamp/Time.cpp.i
.PHONY : src/Timestamp/Time.cpp.i

src/Timestamp/Time.s: src/Timestamp/Time.cpp.s
.PHONY : src/Timestamp/Time.s

# target to generate assembly for a file
src/Timestamp/Time.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\AgendaApp.dir\build.make CMakeFiles/AgendaApp.dir/src/Timestamp/Time.cpp.s
.PHONY : src/Timestamp/Time.cpp.s

src/Utils.obj: src/Utils.cpp.obj
.PHONY : src/Utils.obj

# target to build an object file
src/Utils.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\AgendaApp.dir\build.make CMakeFiles/AgendaApp.dir/src/Utils.cpp.obj
.PHONY : src/Utils.cpp.obj

src/Utils.i: src/Utils.cpp.i
.PHONY : src/Utils.i

# target to preprocess a source file
src/Utils.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\AgendaApp.dir\build.make CMakeFiles/AgendaApp.dir/src/Utils.cpp.i
.PHONY : src/Utils.cpp.i

src/Utils.s: src/Utils.cpp.s
.PHONY : src/Utils.s

# target to generate assembly for a file
src/Utils.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\AgendaApp.dir\build.make CMakeFiles/AgendaApp.dir/src/Utils.cpp.s
.PHONY : src/Utils.cpp.s

src/statemachine/MenuState.obj: src/statemachine/MenuState.cpp.obj
.PHONY : src/statemachine/MenuState.obj

# target to build an object file
src/statemachine/MenuState.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\AgendaApp.dir\build.make CMakeFiles/AgendaApp.dir/src/statemachine/MenuState.cpp.obj
.PHONY : src/statemachine/MenuState.cpp.obj

src/statemachine/MenuState.i: src/statemachine/MenuState.cpp.i
.PHONY : src/statemachine/MenuState.i

# target to preprocess a source file
src/statemachine/MenuState.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\AgendaApp.dir\build.make CMakeFiles/AgendaApp.dir/src/statemachine/MenuState.cpp.i
.PHONY : src/statemachine/MenuState.cpp.i

src/statemachine/MenuState.s: src/statemachine/MenuState.cpp.s
.PHONY : src/statemachine/MenuState.s

# target to generate assembly for a file
src/statemachine/MenuState.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\AgendaApp.dir\build.make CMakeFiles/AgendaApp.dir/src/statemachine/MenuState.cpp.s
.PHONY : src/statemachine/MenuState.cpp.s

src/statemachine/StateMachine.obj: src/statemachine/StateMachine.cpp.obj
.PHONY : src/statemachine/StateMachine.obj

# target to build an object file
src/statemachine/StateMachine.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\AgendaApp.dir\build.make CMakeFiles/AgendaApp.dir/src/statemachine/StateMachine.cpp.obj
.PHONY : src/statemachine/StateMachine.cpp.obj

src/statemachine/StateMachine.i: src/statemachine/StateMachine.cpp.i
.PHONY : src/statemachine/StateMachine.i

# target to preprocess a source file
src/statemachine/StateMachine.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\AgendaApp.dir\build.make CMakeFiles/AgendaApp.dir/src/statemachine/StateMachine.cpp.i
.PHONY : src/statemachine/StateMachine.cpp.i

src/statemachine/StateMachine.s: src/statemachine/StateMachine.cpp.s
.PHONY : src/statemachine/StateMachine.s

# target to generate assembly for a file
src/statemachine/StateMachine.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\AgendaApp.dir\build.make CMakeFiles/AgendaApp.dir/src/statemachine/StateMachine.cpp.s
.PHONY : src/statemachine/StateMachine.cpp.s

src/statemachine/states/AddEventState.obj: src/statemachine/states/AddEventState.cpp.obj
.PHONY : src/statemachine/states/AddEventState.obj

# target to build an object file
src/statemachine/states/AddEventState.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\AgendaApp.dir\build.make CMakeFiles/AgendaApp.dir/src/statemachine/states/AddEventState.cpp.obj
.PHONY : src/statemachine/states/AddEventState.cpp.obj

src/statemachine/states/AddEventState.i: src/statemachine/states/AddEventState.cpp.i
.PHONY : src/statemachine/states/AddEventState.i

# target to preprocess a source file
src/statemachine/states/AddEventState.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\AgendaApp.dir\build.make CMakeFiles/AgendaApp.dir/src/statemachine/states/AddEventState.cpp.i
.PHONY : src/statemachine/states/AddEventState.cpp.i

src/statemachine/states/AddEventState.s: src/statemachine/states/AddEventState.cpp.s
.PHONY : src/statemachine/states/AddEventState.s

# target to generate assembly for a file
src/statemachine/states/AddEventState.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\AgendaApp.dir\build.make CMakeFiles/AgendaApp.dir/src/statemachine/states/AddEventState.cpp.s
.PHONY : src/statemachine/states/AddEventState.cpp.s

src/statemachine/states/ConfirmEventRemovalState.obj: src/statemachine/states/ConfirmEventRemovalState.cpp.obj
.PHONY : src/statemachine/states/ConfirmEventRemovalState.obj

# target to build an object file
src/statemachine/states/ConfirmEventRemovalState.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\AgendaApp.dir\build.make CMakeFiles/AgendaApp.dir/src/statemachine/states/ConfirmEventRemovalState.cpp.obj
.PHONY : src/statemachine/states/ConfirmEventRemovalState.cpp.obj

src/statemachine/states/ConfirmEventRemovalState.i: src/statemachine/states/ConfirmEventRemovalState.cpp.i
.PHONY : src/statemachine/states/ConfirmEventRemovalState.i

# target to preprocess a source file
src/statemachine/states/ConfirmEventRemovalState.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\AgendaApp.dir\build.make CMakeFiles/AgendaApp.dir/src/statemachine/states/ConfirmEventRemovalState.cpp.i
.PHONY : src/statemachine/states/ConfirmEventRemovalState.cpp.i

src/statemachine/states/ConfirmEventRemovalState.s: src/statemachine/states/ConfirmEventRemovalState.cpp.s
.PHONY : src/statemachine/states/ConfirmEventRemovalState.s

# target to generate assembly for a file
src/statemachine/states/ConfirmEventRemovalState.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\AgendaApp.dir\build.make CMakeFiles/AgendaApp.dir/src/statemachine/states/ConfirmEventRemovalState.cpp.s
.PHONY : src/statemachine/states/ConfirmEventRemovalState.cpp.s

src/statemachine/states/ConfirmQuitState.obj: src/statemachine/states/ConfirmQuitState.cpp.obj
.PHONY : src/statemachine/states/ConfirmQuitState.obj

# target to build an object file
src/statemachine/states/ConfirmQuitState.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\AgendaApp.dir\build.make CMakeFiles/AgendaApp.dir/src/statemachine/states/ConfirmQuitState.cpp.obj
.PHONY : src/statemachine/states/ConfirmQuitState.cpp.obj

src/statemachine/states/ConfirmQuitState.i: src/statemachine/states/ConfirmQuitState.cpp.i
.PHONY : src/statemachine/states/ConfirmQuitState.i

# target to preprocess a source file
src/statemachine/states/ConfirmQuitState.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\AgendaApp.dir\build.make CMakeFiles/AgendaApp.dir/src/statemachine/states/ConfirmQuitState.cpp.i
.PHONY : src/statemachine/states/ConfirmQuitState.cpp.i

src/statemachine/states/ConfirmQuitState.s: src/statemachine/states/ConfirmQuitState.cpp.s
.PHONY : src/statemachine/states/ConfirmQuitState.s

# target to generate assembly for a file
src/statemachine/states/ConfirmQuitState.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\AgendaApp.dir\build.make CMakeFiles/AgendaApp.dir/src/statemachine/states/ConfirmQuitState.cpp.s
.PHONY : src/statemachine/states/ConfirmQuitState.cpp.s

src/statemachine/states/EditAgendaState.obj: src/statemachine/states/EditAgendaState.cpp.obj
.PHONY : src/statemachine/states/EditAgendaState.obj

# target to build an object file
src/statemachine/states/EditAgendaState.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\AgendaApp.dir\build.make CMakeFiles/AgendaApp.dir/src/statemachine/states/EditAgendaState.cpp.obj
.PHONY : src/statemachine/states/EditAgendaState.cpp.obj

src/statemachine/states/EditAgendaState.i: src/statemachine/states/EditAgendaState.cpp.i
.PHONY : src/statemachine/states/EditAgendaState.i

# target to preprocess a source file
src/statemachine/states/EditAgendaState.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\AgendaApp.dir\build.make CMakeFiles/AgendaApp.dir/src/statemachine/states/EditAgendaState.cpp.i
.PHONY : src/statemachine/states/EditAgendaState.cpp.i

src/statemachine/states/EditAgendaState.s: src/statemachine/states/EditAgendaState.cpp.s
.PHONY : src/statemachine/states/EditAgendaState.s

# target to generate assembly for a file
src/statemachine/states/EditAgendaState.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\AgendaApp.dir\build.make CMakeFiles/AgendaApp.dir/src/statemachine/states/EditAgendaState.cpp.s
.PHONY : src/statemachine/states/EditAgendaState.cpp.s

src/statemachine/states/ExportHTMLState.obj: src/statemachine/states/ExportHTMLState.cpp.obj
.PHONY : src/statemachine/states/ExportHTMLState.obj

# target to build an object file
src/statemachine/states/ExportHTMLState.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\AgendaApp.dir\build.make CMakeFiles/AgendaApp.dir/src/statemachine/states/ExportHTMLState.cpp.obj
.PHONY : src/statemachine/states/ExportHTMLState.cpp.obj

src/statemachine/states/ExportHTMLState.i: src/statemachine/states/ExportHTMLState.cpp.i
.PHONY : src/statemachine/states/ExportHTMLState.i

# target to preprocess a source file
src/statemachine/states/ExportHTMLState.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\AgendaApp.dir\build.make CMakeFiles/AgendaApp.dir/src/statemachine/states/ExportHTMLState.cpp.i
.PHONY : src/statemachine/states/ExportHTMLState.cpp.i

src/statemachine/states/ExportHTMLState.s: src/statemachine/states/ExportHTMLState.cpp.s
.PHONY : src/statemachine/states/ExportHTMLState.s

# target to generate assembly for a file
src/statemachine/states/ExportHTMLState.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\AgendaApp.dir\build.make CMakeFiles/AgendaApp.dir/src/statemachine/states/ExportHTMLState.cpp.s
.PHONY : src/statemachine/states/ExportHTMLState.cpp.s

src/statemachine/states/MainMenuState.obj: src/statemachine/states/MainMenuState.cpp.obj
.PHONY : src/statemachine/states/MainMenuState.obj

# target to build an object file
src/statemachine/states/MainMenuState.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\AgendaApp.dir\build.make CMakeFiles/AgendaApp.dir/src/statemachine/states/MainMenuState.cpp.obj
.PHONY : src/statemachine/states/MainMenuState.cpp.obj

src/statemachine/states/MainMenuState.i: src/statemachine/states/MainMenuState.cpp.i
.PHONY : src/statemachine/states/MainMenuState.i

# target to preprocess a source file
src/statemachine/states/MainMenuState.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\AgendaApp.dir\build.make CMakeFiles/AgendaApp.dir/src/statemachine/states/MainMenuState.cpp.i
.PHONY : src/statemachine/states/MainMenuState.cpp.i

src/statemachine/states/MainMenuState.s: src/statemachine/states/MainMenuState.cpp.s
.PHONY : src/statemachine/states/MainMenuState.s

# target to generate assembly for a file
src/statemachine/states/MainMenuState.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\AgendaApp.dir\build.make CMakeFiles/AgendaApp.dir/src/statemachine/states/MainMenuState.cpp.s
.PHONY : src/statemachine/states/MainMenuState.cpp.s

src/statemachine/states/QuitState.obj: src/statemachine/states/QuitState.cpp.obj
.PHONY : src/statemachine/states/QuitState.obj

# target to build an object file
src/statemachine/states/QuitState.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\AgendaApp.dir\build.make CMakeFiles/AgendaApp.dir/src/statemachine/states/QuitState.cpp.obj
.PHONY : src/statemachine/states/QuitState.cpp.obj

src/statemachine/states/QuitState.i: src/statemachine/states/QuitState.cpp.i
.PHONY : src/statemachine/states/QuitState.i

# target to preprocess a source file
src/statemachine/states/QuitState.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\AgendaApp.dir\build.make CMakeFiles/AgendaApp.dir/src/statemachine/states/QuitState.cpp.i
.PHONY : src/statemachine/states/QuitState.cpp.i

src/statemachine/states/QuitState.s: src/statemachine/states/QuitState.cpp.s
.PHONY : src/statemachine/states/QuitState.s

# target to generate assembly for a file
src/statemachine/states/QuitState.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\AgendaApp.dir\build.make CMakeFiles/AgendaApp.dir/src/statemachine/states/QuitState.cpp.s
.PHONY : src/statemachine/states/QuitState.cpp.s

src/statemachine/states/RemoveEventByIDState.obj: src/statemachine/states/RemoveEventByIDState.cpp.obj
.PHONY : src/statemachine/states/RemoveEventByIDState.obj

# target to build an object file
src/statemachine/states/RemoveEventByIDState.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\AgendaApp.dir\build.make CMakeFiles/AgendaApp.dir/src/statemachine/states/RemoveEventByIDState.cpp.obj
.PHONY : src/statemachine/states/RemoveEventByIDState.cpp.obj

src/statemachine/states/RemoveEventByIDState.i: src/statemachine/states/RemoveEventByIDState.cpp.i
.PHONY : src/statemachine/states/RemoveEventByIDState.i

# target to preprocess a source file
src/statemachine/states/RemoveEventByIDState.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\AgendaApp.dir\build.make CMakeFiles/AgendaApp.dir/src/statemachine/states/RemoveEventByIDState.cpp.i
.PHONY : src/statemachine/states/RemoveEventByIDState.cpp.i

src/statemachine/states/RemoveEventByIDState.s: src/statemachine/states/RemoveEventByIDState.cpp.s
.PHONY : src/statemachine/states/RemoveEventByIDState.s

# target to generate assembly for a file
src/statemachine/states/RemoveEventByIDState.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\AgendaApp.dir\build.make CMakeFiles/AgendaApp.dir/src/statemachine/states/RemoveEventByIDState.cpp.s
.PHONY : src/statemachine/states/RemoveEventByIDState.cpp.s

src/statemachine/states/RemoveEventByNameState.obj: src/statemachine/states/RemoveEventByNameState.cpp.obj
.PHONY : src/statemachine/states/RemoveEventByNameState.obj

# target to build an object file
src/statemachine/states/RemoveEventByNameState.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\AgendaApp.dir\build.make CMakeFiles/AgendaApp.dir/src/statemachine/states/RemoveEventByNameState.cpp.obj
.PHONY : src/statemachine/states/RemoveEventByNameState.cpp.obj

src/statemachine/states/RemoveEventByNameState.i: src/statemachine/states/RemoveEventByNameState.cpp.i
.PHONY : src/statemachine/states/RemoveEventByNameState.i

# target to preprocess a source file
src/statemachine/states/RemoveEventByNameState.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\AgendaApp.dir\build.make CMakeFiles/AgendaApp.dir/src/statemachine/states/RemoveEventByNameState.cpp.i
.PHONY : src/statemachine/states/RemoveEventByNameState.cpp.i

src/statemachine/states/RemoveEventByNameState.s: src/statemachine/states/RemoveEventByNameState.cpp.s
.PHONY : src/statemachine/states/RemoveEventByNameState.s

# target to generate assembly for a file
src/statemachine/states/RemoveEventByNameState.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\AgendaApp.dir\build.make CMakeFiles/AgendaApp.dir/src/statemachine/states/RemoveEventByNameState.cpp.s
.PHONY : src/statemachine/states/RemoveEventByNameState.cpp.s

src/statemachine/states/RemoveEventMenuState.obj: src/statemachine/states/RemoveEventMenuState.cpp.obj
.PHONY : src/statemachine/states/RemoveEventMenuState.obj

# target to build an object file
src/statemachine/states/RemoveEventMenuState.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\AgendaApp.dir\build.make CMakeFiles/AgendaApp.dir/src/statemachine/states/RemoveEventMenuState.cpp.obj
.PHONY : src/statemachine/states/RemoveEventMenuState.cpp.obj

src/statemachine/states/RemoveEventMenuState.i: src/statemachine/states/RemoveEventMenuState.cpp.i
.PHONY : src/statemachine/states/RemoveEventMenuState.i

# target to preprocess a source file
src/statemachine/states/RemoveEventMenuState.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\AgendaApp.dir\build.make CMakeFiles/AgendaApp.dir/src/statemachine/states/RemoveEventMenuState.cpp.i
.PHONY : src/statemachine/states/RemoveEventMenuState.cpp.i

src/statemachine/states/RemoveEventMenuState.s: src/statemachine/states/RemoveEventMenuState.cpp.s
.PHONY : src/statemachine/states/RemoveEventMenuState.s

# target to generate assembly for a file
src/statemachine/states/RemoveEventMenuState.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\AgendaApp.dir\build.make CMakeFiles/AgendaApp.dir/src/statemachine/states/RemoveEventMenuState.cpp.s
.PHONY : src/statemachine/states/RemoveEventMenuState.cpp.s

src/statemachine/states/RemoveEventState.obj: src/statemachine/states/RemoveEventState.cpp.obj
.PHONY : src/statemachine/states/RemoveEventState.obj

# target to build an object file
src/statemachine/states/RemoveEventState.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\AgendaApp.dir\build.make CMakeFiles/AgendaApp.dir/src/statemachine/states/RemoveEventState.cpp.obj
.PHONY : src/statemachine/states/RemoveEventState.cpp.obj

src/statemachine/states/RemoveEventState.i: src/statemachine/states/RemoveEventState.cpp.i
.PHONY : src/statemachine/states/RemoveEventState.i

# target to preprocess a source file
src/statemachine/states/RemoveEventState.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\AgendaApp.dir\build.make CMakeFiles/AgendaApp.dir/src/statemachine/states/RemoveEventState.cpp.i
.PHONY : src/statemachine/states/RemoveEventState.cpp.i

src/statemachine/states/RemoveEventState.s: src/statemachine/states/RemoveEventState.cpp.s
.PHONY : src/statemachine/states/RemoveEventState.s

# target to generate assembly for a file
src/statemachine/states/RemoveEventState.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\AgendaApp.dir\build.make CMakeFiles/AgendaApp.dir/src/statemachine/states/RemoveEventState.cpp.s
.PHONY : src/statemachine/states/RemoveEventState.cpp.s

src/statemachine/states/SaveAgendaState.obj: src/statemachine/states/SaveAgendaState.cpp.obj
.PHONY : src/statemachine/states/SaveAgendaState.obj

# target to build an object file
src/statemachine/states/SaveAgendaState.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\AgendaApp.dir\build.make CMakeFiles/AgendaApp.dir/src/statemachine/states/SaveAgendaState.cpp.obj
.PHONY : src/statemachine/states/SaveAgendaState.cpp.obj

src/statemachine/states/SaveAgendaState.i: src/statemachine/states/SaveAgendaState.cpp.i
.PHONY : src/statemachine/states/SaveAgendaState.i

# target to preprocess a source file
src/statemachine/states/SaveAgendaState.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\AgendaApp.dir\build.make CMakeFiles/AgendaApp.dir/src/statemachine/states/SaveAgendaState.cpp.i
.PHONY : src/statemachine/states/SaveAgendaState.cpp.i

src/statemachine/states/SaveAgendaState.s: src/statemachine/states/SaveAgendaState.cpp.s
.PHONY : src/statemachine/states/SaveAgendaState.s

# target to generate assembly for a file
src/statemachine/states/SaveAgendaState.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\AgendaApp.dir\build.make CMakeFiles/AgendaApp.dir/src/statemachine/states/SaveAgendaState.cpp.s
.PHONY : src/statemachine/states/SaveAgendaState.cpp.s

src/statemachine/states/ShowAgendaState.obj: src/statemachine/states/ShowAgendaState.cpp.obj
.PHONY : src/statemachine/states/ShowAgendaState.obj

# target to build an object file
src/statemachine/states/ShowAgendaState.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\AgendaApp.dir\build.make CMakeFiles/AgendaApp.dir/src/statemachine/states/ShowAgendaState.cpp.obj
.PHONY : src/statemachine/states/ShowAgendaState.cpp.obj

src/statemachine/states/ShowAgendaState.i: src/statemachine/states/ShowAgendaState.cpp.i
.PHONY : src/statemachine/states/ShowAgendaState.i

# target to preprocess a source file
src/statemachine/states/ShowAgendaState.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\AgendaApp.dir\build.make CMakeFiles/AgendaApp.dir/src/statemachine/states/ShowAgendaState.cpp.i
.PHONY : src/statemachine/states/ShowAgendaState.cpp.i

src/statemachine/states/ShowAgendaState.s: src/statemachine/states/ShowAgendaState.cpp.s
.PHONY : src/statemachine/states/ShowAgendaState.s

# target to generate assembly for a file
src/statemachine/states/ShowAgendaState.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\AgendaApp.dir\build.make CMakeFiles/AgendaApp.dir/src/statemachine/states/ShowAgendaState.cpp.s
.PHONY : src/statemachine/states/ShowAgendaState.cpp.s

# Help Target
help:
	@echo The following are some of the valid targets for this Makefile:
	@echo ... all (the default if no target is provided)
	@echo ... clean
	@echo ... depend
	@echo ... edit_cache
	@echo ... rebuild_cache
	@echo ... AgendaApp
	@echo ... src/Agenda/Agenda.obj
	@echo ... src/Agenda/Agenda.i
	@echo ... src/Agenda/Agenda.s
	@echo ... src/Agenda/Controller.obj
	@echo ... src/Agenda/Controller.i
	@echo ... src/Agenda/Controller.s
	@echo ... src/Events/Event.obj
	@echo ... src/Events/Event.i
	@echo ... src/Events/Event.s
	@echo ... src/Events/EventsList.obj
	@echo ... src/Events/EventsList.i
	@echo ... src/Events/EventsList.s
	@echo ... src/Main.obj
	@echo ... src/Main.i
	@echo ... src/Main.s
	@echo ... src/MultiString.obj
	@echo ... src/MultiString.i
	@echo ... src/MultiString.s
	@echo ... src/ResourceManager.obj
	@echo ... src/ResourceManager.i
	@echo ... src/ResourceManager.s
	@echo ... src/Timestamp/Date.obj
	@echo ... src/Timestamp/Date.i
	@echo ... src/Timestamp/Date.s
	@echo ... src/Timestamp/Time.obj
	@echo ... src/Timestamp/Time.i
	@echo ... src/Timestamp/Time.s
	@echo ... src/Utils.obj
	@echo ... src/Utils.i
	@echo ... src/Utils.s
	@echo ... src/statemachine/MenuState.obj
	@echo ... src/statemachine/MenuState.i
	@echo ... src/statemachine/MenuState.s
	@echo ... src/statemachine/StateMachine.obj
	@echo ... src/statemachine/StateMachine.i
	@echo ... src/statemachine/StateMachine.s
	@echo ... src/statemachine/states/AddEventState.obj
	@echo ... src/statemachine/states/AddEventState.i
	@echo ... src/statemachine/states/AddEventState.s
	@echo ... src/statemachine/states/ConfirmEventRemovalState.obj
	@echo ... src/statemachine/states/ConfirmEventRemovalState.i
	@echo ... src/statemachine/states/ConfirmEventRemovalState.s
	@echo ... src/statemachine/states/ConfirmQuitState.obj
	@echo ... src/statemachine/states/ConfirmQuitState.i
	@echo ... src/statemachine/states/ConfirmQuitState.s
	@echo ... src/statemachine/states/EditAgendaState.obj
	@echo ... src/statemachine/states/EditAgendaState.i
	@echo ... src/statemachine/states/EditAgendaState.s
	@echo ... src/statemachine/states/ExportHTMLState.obj
	@echo ... src/statemachine/states/ExportHTMLState.i
	@echo ... src/statemachine/states/ExportHTMLState.s
	@echo ... src/statemachine/states/MainMenuState.obj
	@echo ... src/statemachine/states/MainMenuState.i
	@echo ... src/statemachine/states/MainMenuState.s
	@echo ... src/statemachine/states/QuitState.obj
	@echo ... src/statemachine/states/QuitState.i
	@echo ... src/statemachine/states/QuitState.s
	@echo ... src/statemachine/states/RemoveEventByIDState.obj
	@echo ... src/statemachine/states/RemoveEventByIDState.i
	@echo ... src/statemachine/states/RemoveEventByIDState.s
	@echo ... src/statemachine/states/RemoveEventByNameState.obj
	@echo ... src/statemachine/states/RemoveEventByNameState.i
	@echo ... src/statemachine/states/RemoveEventByNameState.s
	@echo ... src/statemachine/states/RemoveEventMenuState.obj
	@echo ... src/statemachine/states/RemoveEventMenuState.i
	@echo ... src/statemachine/states/RemoveEventMenuState.s
	@echo ... src/statemachine/states/RemoveEventState.obj
	@echo ... src/statemachine/states/RemoveEventState.i
	@echo ... src/statemachine/states/RemoveEventState.s
	@echo ... src/statemachine/states/SaveAgendaState.obj
	@echo ... src/statemachine/states/SaveAgendaState.i
	@echo ... src/statemachine/states/SaveAgendaState.s
	@echo ... src/statemachine/states/ShowAgendaState.obj
	@echo ... src/statemachine/states/ShowAgendaState.i
	@echo ... src/statemachine/states/ShowAgendaState.s
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 0
.PHONY : cmake_check_build_system

